In [1]:
import pandas as pd
from sqlalchemy import create_engine

## Extract CSVs into Dataframes

In [3]:
bike_file = "Resources/austin_bikeshare_trips.csv"
trips_df = pd.read_csv(bike_file)
trips_df.head()

,bikeid,checkout_time,duration_minutes,end_station_id,end_station_name,month,start_station_id,start_station_name,start_time,subscriber_type,trip_id,year
0,8.0,19:12:00,41,2565.0,Trinity & 6th Street,3.0,2536.0,Waller & 6th St.,2015-03-19 19:12:00,Walk Up,9900082882,2015.0
1,141.0,2:06:04,6,2570.0,South Congress & Academy,10.0,2494.0,2nd & Congress,2016-10-30 02:06:04,Local365,12617682,2016.0
2,578.0,16:28:27,13,2498.0,Convention Center / 4th St. @ MetroRail,3.0,2538.0,Bullock Museum @ Congress & MLK,2016-03-11 16:28:27,Local365,9075366,2016.0
3,555.0,15:12:00,80,2712.0,Toomey Rd @ South Lamar,11.0,2497.0,Capitol Station / Congress & 11th,2014-11-23 15:12:00,24-Hour Kiosk (Austin B-cycle),9900319298,2014.0
4,86.0,15:39:13,25,3377.0,MoPac Pedestrian Bridge @ Veterans Drive,4.0,2707.0,Rainey St @ Cummings,2017-04-16 15:39:13,Walk Up,14468597,2017.0

In [4]:
bike_file2 = "Resources/austin_bikeshare_stations.csv"
stations_df = pd.read_csv(bike_file2)
stations_df.head()

,latitude,location,longitude,name,station_id,status
0,30.25457,(30.25457 -97.74258),-97.74258,Boardwalk West,3687,active
1,30.26406,(30.26406 -97.76385),-97.76385,Sterzing at Barton Springs,3686,active
2,30.27217,(30.27217 -97.75246),-97.75246,Henderson & 9th,3685,active
3,30.26332,(30.26332 -97.74508),-97.74508,Congress & Cesar Chavez,3684,active
4,30.26455,(30.26455 -97.73165),-97.73165,Medina & East 6th,3660,active

### Transform premise DataFrame

In [ ]:
# Reducing years to, 2016 and 2017
trips_df